# Generated by Django 3.2.5 on 2021-09-19 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import petprofile.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Species',
            },
        ),
        migrations.CreateModel(
            name='PetProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petName', models.CharField(max_length=30, verbose_name='Nume')),
                ('petSlug', models.SlugField(unique=True)),
                ('petGender', models.CharField(choices=[('M', 'mascul'), ('F', 'femela'), ('N', 'nespecificat')], max_length=10, verbose_name='Gen')),
                ('petDescription', models.TextField(max_length=2000, verbose_name='Scurta descriere')),
                ('petPhoto', models.ImageField(blank=True, default='petprofile-photo/avatar.png', upload_to=petprofile.models._img_dir_path, verbose_name='Foto')),
                ('petProfileCreationDate', models.DateField(auto_now_add=True, verbose_name='Data creare profil')),
                ('PetProfileUpdateDate', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('petBreed', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='petprofile.breed', verbose_name='Subspecie/Rasa')),
                ('petLikes', models.ManyToManyField(blank=True, related_name='profileLikes', to=settings.AUTH_USER_MODEL, verbose_name='Likes')),
                ('petSpecies', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='petprofile.species', verbose_name='Categorie')),
            ],
        ),
        migrations.AddField(
            model_name='breed',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='petprofile.species'),
        ),
    ]
