# Generated by Django 3.2.5 on 2021-10-24 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petprofile', '0005_auto_20211022_0630'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breed',
            options={'ordering': ('breed_name',)},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='species',
            options={'ordering': ('species_name',), 'verbose_name_plural': 'species'},
        ),
    ]
