# Generated by Django 3.2.5 on 2021-11-03 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petprofile', '0007_alter_breed_breed_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breed',
            options={'ordering': ['breed_name']},
        ),
        migrations.AlterModelOptions(
            name='species',
            options={'ordering': ['species_name'], 'verbose_name_plural': 'species'},
        ),
    ]
