# Generated by Django 3.2.5 on 2021-11-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petprofile', '0008_auto_20211103_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petprofile',
            name='petGender',
            field=models.CharField(choices=[('M', 'Mascul'), ('F', 'Femela'), ('N', 'Nespecificat')], max_length=10, verbose_name='Gen'),
        ),
    ]
