# Generated by Django 3.2.5 on 2021-11-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petprofile', '0009_alter_petprofile_petgender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petprofile',
            name='petSlug',
            field=models.SlugField(max_length=120, unique=True),
        ),
    ]
