# Generated by Django 3.2.5 on 2021-11-21 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petprofile', '0011_auto_20211121_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_main_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='petprofile.comment'),
        ),
    ]
