# Generated by Django 3.2.5 on 2021-12-04 21:46

from django.db import migrations, models
import django.db.models.deletion
import petprofile.models


class Migration(migrations.Migration):

    dependencies = [
        ('petprofile', '0012_comment_comment_main_thread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petprofile',
            name='petPhoto',
            field=models.ImageField(blank=True, default='petprofile-photo/avatar.png', max_length=200, upload_to=petprofile.models._img_dir_path, verbose_name='Foto'),
        ),
        migrations.CreateModel(
            name='PetProfileExtraImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petExtraImg', models.ImageField(max_length=200, upload_to=petprofile.models._extra_img_dir_path, verbose_name='PetExtraImg')),
                ('petProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_imgs', to='petprofile.petprofile')),
            ],
        ),
    ]
